version: '3'
services:
  db:
    image: postgres:10.1-alpine
    # restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  text2embeddings:
    build:
      context: .
      dockerfile: ./text2embeddings/Dockerfile
    environment:
      - NATS_URI=${NATS_URI}
    depends_on:
      - nats
    links:
      - nats

  nats:
    image: 'nats:1.4.1'
    command: >
       --cluster nats://0.0.0.0:6222 --http_port 8222 
       $NATS_AUTH_PARAMS
    environment:
      - NATS_AUTH_PARAMS=${NATS_AUTH_PARAMS}
    # networks: ["nats"]
    
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    # restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NATS_URI=${NATS_URI}
    depends_on:
      - db
      - text2embeddings
    links:
      - db